import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({ variable:"--font-geist-sans", subsets:["latin"] });
const geistMono = Geist_Mono({ variable:"--font-geist-mono", subsets:["latin"] });
export const metadata: Metadata = { title:"PR Sentinel — AI Pull Request Intelligence", description:"AI-powered pull request intelligence for GitHub teams." };

export default function RootLayout({ children }: LayoutProps<"/">) { return <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}><body className="min-h-full font-sans"><header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/80 backdrop-blur-xl"><nav className="mx-auto flex h-[68px] max-w-7xl items-center justify-between px-5 sm:px-8" aria-label="Primary navigation"><Link href="/" className="flex items-center gap-2.5 rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"><span aria-hidden className="grid size-8 place-items-center rounded-[10px] bg-indigo-600 text-sm font-bold text-white shadow-sm shadow-indigo-300">S</span><span className="text-[15px] font-semibold tracking-[-.025em] text-slate-900">PR Sentinel</span></Link><div className="flex items-center gap-1"><Link href="/" className="rounded-lg px-3 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-100 hover:text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">Dashboard</Link><Link href="/#repositories" className="rounded-lg px-3 py-2 text-sm font-medium text-slate-500 transition hover:bg-slate-100 hover:text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">Repositories</Link></div><div className="hidden items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-medium text-emerald-700 sm:flex"><span className="size-1.5 rounded-full bg-emerald-500 shadow-[0_0_0_3px_rgba(34,197,94,.12)]"/>AI Review Engine</div></nav></header><div className="flex-1">{children}</div></body></html>; }
