"""initial schema: users, repos, code_chunks, pull_requests, reviews, findings, agent_traces, eval tables

Revision ID: b17c4f1e4706
Revises: 2e4fa044b083
Create Date: 2026-09-06 13:28:31.195049

"""
from typing import Sequence, Union
import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17c4f1e4706'
down_revision: Union[str, Sequence[str], None] = '2e4fa044b083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_reference', sa.String(length=500), nullable=False),
    sa.Column('ground_truth_findings_json', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('false_positive_rate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repos_full_name'), 'repos', ['full_name'], unique=False)
    op.create_index(op.f('ix_repos_github_repo_id'), 'repos', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_repos_installation_id'), 'repos', ['installation_id'], unique=False)
    op.create_table('code_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_chunks_repo_id'), 'code_chunks', ['repo_id'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('github_pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_requests_repo_id'), 'pull_requests', ['repo_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('turns_taken', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_pr_id'), 'reviews', ['pr_id'], unique=False)
    op.create_table('agent_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('tool_calls_json', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_review_id'), 'agent_traces', ['review_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=1000), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_review_id'), 'findings', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_review_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_agent_traces_review_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index(op.f('ix_reviews_pr_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_pull_requests_repo_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_code_chunks_repo_id'), table_name='code_chunks')
    op.drop_table('code_chunks')
    op.drop_index(op.f('ix_repos_installation_id'), table_name='repos')
    op.drop_index(op.f('ix_repos_github_repo_id'), table_name='repos')
    op.drop_index(op.f('ix_repos_full_name'), table_name='repos')
    op.drop_table('repos')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('eval_runs')
    op.drop_table('eval_labels')
    # ### end Alembic commands ###
